### ISSUE TITLE
Server error 500

### ISSUE THREAD

**Issue by Organizer21** [tin-cat/emailqueue#11]
Hi there, this might not be an issue and more my setup, but is there a way to enable some sort of debug output of the delivery part?

I've a dedicated host running PLESK and I have a domain setup with email (email works fine with outlook, secure, port authentication required on 465 etc.). I unzipped your package to a folder, did the configuration, database setup and download PHPMailer from their git, dumped those files into the PHPMailer folder you had.

Now emails are added to the queue/db, the cron is triggered, the email gets flagged as being in process of being sent but nothing happens after that and it remains as "sending now". If I run the delivery.php directly in my browser it takes some time, 30 sec maybe before it gives me a server 500 error message (so I guess the issue is there). BTW if I run it without an email pending it will give me some output;

Emailqueue · Delivery
Maximum delivery timeout: 50 sec.
Delivery interval: 0,10 seconds
Maximum emails to deliver: 1000
Process started on: 19/1/2017 22:40.55
No emails on queue.
Process ended on: 19/1/2017 22:40.55

I've tried with SMTP_SERVER set to localhost, 127.0.0.1 and the server IP with same result. I've not configured anything with PHPMailer as I presumed that's controlled by your system. The timeout only happens with port 465 (which is what I use), using any other port gives a "Could not connect to SMTP host." and similar

**UPDATED; foud this from my general server log:** 
`2017-01-20 00:03:04	Error	myip	500	GET /assets/custom/plugins/emailqueue/scripts/delivery.php HTTP/1.0	1.76 K	Apache SSL access

2017-01-20 00:03:50	Warning	myip		mod_fcgid: read data timeout in 45 seconds				Apache error

2017-01-20 00:03:50	Error	myip		End of script output before headers: delivery.php				Apache error`

From where I am, what I did to install, and the error 500 received only when it tried to process an email, any clue as to get some error debug output or what I can try next? 

Chris

**Comment by tin-cat** [comment]
Hi @Organizer21, it definitely looks you have a lot going on there! It seems you're dealing with server admin issues of many kinds outside EmailQueue itself, and that would take quite a long time to understand and analyze in order to be able to help you. I'm sorry I cannot provide that kind of in-depth support :(

Just a quick hint:

Don't run delivery.php via browser or via wget, it is a script intended to be executed with the PHP CLI, use the provided "delivery" shell script (edit and modify it to your specific server environment with the proper paths) That seems to be the source of more than one of the issues you're having.
