### ISSUE TITLE
Attachments already in base64 without file on filesystem

### ISSUE THREAD

**Issue by SuperSpe** [tin-cat/emailqueue#14]
Is it possible to add an attachment already in base64 format and not as a file on the filesystem?
I'm asking because I'm not saving the file to the hd but generated on the fly to save space and issue
thanks

**Comment by tin-cat** [comment]
Hi! That's a great idea! Emailqueue does not allows this, but you can add this functionality relatively easy, take a look at:

scripts/emailqueue_inject.class.php (lines 72-88 and line 126 and line 155)
scripts/delivery.php (lines 230-262)

At first glance, modifications should be done to the mentioned files to add this functionality. Also, database should be modified in order to hold the base64 files (That would potentially increase the db size), since the current system only stores the path to the files on the database instead of the attached files itself.

I invite you to do this modifications and request a merge!

Cheers!

**Comment by SuperSpe** [comment]
Ok I will give a try. But I think I have to add some other headers and the boundary...
