### ISSUE TITLE
Return-Path

### ISSUE THREAD

**Issue by Andrewsuares** [tin-cat/emailqueue#22]
Hello,

I configured the script to use either one to set the Return-Path and it does not work. I am on PHP 7.3.  Does anyone know of a fix for this. Thanks.

$mail->addCustomHeader('Return-Path: <bounce@something.com>');
OR
$this->mail->Sender = 'bounce@something.com';

**Comment by Andrewsuares** [comment]
Just add this line in the common.inc.php file and the Return-Path works!

$mail->Sender = 'bounce@something.com';

**Comment by tin-cat** [comment]
Hi @Andrewsuares, the only way Emailqueue provides for specifying a sender email is via the `from` and `from_name` setup keys in the [emailqueue_inject::inject](https://github.com/tin-cat/emailqueue#emailqueue-injection-keys) method.

I think what you're trying to do is to send an email using the PHPMailer library. Event though Emailqueue uses PHPMailer internally to send emails, please note that if you are sending mails via emailqueue you must use either the provided [emailqueue_inject](emailqueue_inject) class, or the [emailqueue API](emailqueue_inject). Check out the README for more information on this.

Please note that if you're sending emails using PHPMailer, you're most certainly not using Emailqueue!

Hope this helps you. Cheers!

**Comment by Andrewsuares** [comment]
I do use the inject class. But the class does not have a parameter for the Return-Path or Sender which is very different. Sender is not the same as from. I want to receive bounced email at another email which is NOT the same email as the from or reply-to.

I set this $mail->Sender = 'bounce@something.com'; in the common.inc.php

I now receive bounced email at that email and the from and reply-to is a different email.

**Comment by tin-cat** [comment]
Ah ok, I see the problem now! This should be something to be added to Emailqueue, I agree with you this is a quite important header. I'll keep this issue open, so I hope this feature is added in some upcoming update!

Thanks for contributing!

**Comment by tin-cat** [comment]
Hi Andrew! Thanks for noting this, it is indeed useful to be able to configure this header. Although some SMTP servers will set their own Return-path header (like Amazon SES, which changes it to point to their servers, so they're able to track delivery issues), it is indeed solved by setting the "Sender" property of PHPMailer (since the ReturnPath has been deprecated in older versions of PHPMailer, apparently for this same reason).

I've added the option to setup the sender address when queueing emails with Emailqueue, thus causing the Return-path header to be set to that address for SMTP servers supporting it.

This works by passing the `sender` key to the `emailqueue_inject:inject` method, or the `sender` parameter to the API.

This is included in the latest update for Emailqueue version 3.41, please note couple of changes have to be made to the database for this to work, as specified in the [README file](https://github.com/tin-cat/emailqueue#migrate-from-version-33-or-34-to-version-341).

Thanks for your contribution, it will be included in the upcoming 3.41 official release!
