### ISSUE TITLE
Blacklisted Emails Fix

### ISSUE THREAD

**Issue by Andrewsuares** [tin-cat/emailqueue#24]
Hello,

I discovered today that the blacklist email feature did not work. Emails were sent to users who were blacklisted. I am on PHP 7.3.3

Here are the two fixes to get it to work:

1)
function deliver_email(&$mail, $email, $isOutputVerbose = false) {

global $blacklisted_emails; // Declare $blacklisted_emails as a global variable because this array is not sent to the function.

2) Add a return false so that the email is not sent to the blacklisted user.
		// Check black list
		if (isset($blacklisted_emails))
			if (is_array($blacklisted_emails) and in_array(strtolower(trim($email["to"])), $blacklisted_emails)) {
				if ($isOutputVerbose)
					echo " / Black listed";
				add_incidence($email["id"], "Recipient is on the black list: ".$email["to"]);
				cancel($email["id"]);
				$logger->add_log_incidence(
					array(
						$email["id"],
						$email["to"],
						"Email cancelled",
						"Recipient is on the black list"
					)
				);
				return false;
			}

**Comment by tin-cat** [comment]
Hi Andrew, thanks for noting this ugly bug! Instead of using your solution I went for a more performant alternative that checks the blacklist table for every sent email. Specially for scenarios with may blacklisted emails, this should additionally improve performance. Thanks for your contribution! It will be included in the upcoming 3.41 version release!
